version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: distributionbox-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Xjy12345@@
      MYSQL_DATABASE: distributionbox
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: distributionbox-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db_data:
