#  版本号
server:
  ip: 39.107.69.103
  port: 8888

spring:
#  数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://39.107.69.103:3306/box?serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/distribution?serverTimezone=GMT%2b8
    username: root
    password: xjy12345
#    热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  redis:
    port: 6379
    host: 127.0.0.1
  web:
    resources:
      static-locations: file:/home/files/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#  扫描mapper
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件

#   mysql语句可视化
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: /home/files/
    path: F:/IntelliJ IDEA 2021.1.2/shujia-localhost/files/
